RHIROS-1220 Kruize as ClowdApp kind
RedHatInsights/ros-ocp-backend pull request #102
Opened 2023-07-10 17:02 UTC by saltgen

Changes:
Splitting kruize deployment into a new ClowdApp

2023-07-12 07:16 UTC, patilsuraj767 requested changes

2023-07-12 07:16 UTC, patilsuraj767 commented on kruize-clowdapp.yaml
> +      iqePlugin: ros-ocp
I don't think we have any iqe tests specific to kruize so this should be removed.

2023-07-12 07:18 UTC, patilsuraj767 requested changes
On [line 14](https://github.com/RedHatInsights/ros-ocp-backend/blob/main/clowdapp.yaml#L14) in clowdapp file under `dependencies` we should add `kruize` as a dependencies of ros-ocp.

2023-07-12 10:12 UTC, saltgen commented
The ci.int failure is cause of the new dependency `kruize`, guess we need to update the deploy command there?

2023-07-12 12:00 UTC, patilsuraj767 commented
> The ci.int failure is cause of the dependency `kruize`, guess we need to update the deploy command there?

Yeah. so thought regarding it again. All though the kruize is a separate application and has a separate clowdapp fill still it the part of ROS. For app-interface ros-ocp and kruize we still be a single app which means running the `bonfire deploy ros` will also deploy the kruize hence no need to add it as dependency. It can be removed.

2023-07-12 13:19 UTC, saltgen commented
> > The ci.int failure is cause of the dependency `kruize`, guess we need to update the deploy command there?
> 
> Yeah. so I thought regarding it again. All though the kruize is a separate application and has a separate clowdapp file still it the part of ROS. For app-interface ros-ocp and kruize will still be a single app which means running the `bonfire deploy ros` will also deploy the kruize hence no need to add it as dependency. It can be removed.

Change pushed

2023-07-13 04:53 UTC, patilsuraj767 approved these changes
LGTM 👍 Thanks @saltgen

2023-07-13 08:34 UTC, merged