Fixes #RHIROS-1307 - Upgrade kruize image to 0.0.18_rm
RedHatInsights/ros-ocp-backend pull request #119
Opened 2023-08-28 12:32 UTC by patilsuraj767

2023-08-29 09:07 UTC, patilsuraj767 commented
/retest

2023-08-31 05:13 UTC, patilsuraj767 commented
/retest

2023-08-31 06:13 UTC, patilsuraj767 commented
/retest

2023-08-31 07:45 UTC, patilsuraj767 commented
We need - https://github.com/RedHatInsights/cicd-tools/pull/21 to fix the PR check.

2023-08-31 18:26 UTC, saltgen requested changes

2023-08-31 18:26 UTC, saltgen commented on internal/services/report_processor.go
> +	return false
@patilsuraj767 Could we move this function to a utils file?

2023-09-04 06:54 UTC, patilsuraj767 commented on internal/types/kruizePayload/common.go
> +
Added comment on JIRA card.

2023-09-05 07:09 UTC, saltgen approved these changes
LGTM, thanks @patilsuraj767!

2023-09-06 08:33 UTC, patilsuraj767 commented
Thanks for the review @saltgen

2023-09-06 08:33 UTC, merged