Fixes #RHIROS-1402 - Fixed payload creation for kruize updateResult API
RedHatInsights/ros-ocp-backend pull request #142
Opened 2023-10-26 10:57 UTC by patilsuraj767

2023-10-26 11:27 UTC, patilsuraj767 commented
/retest

2023-10-26 14:53 UTC, patilsuraj767 commented
/retest

2023-10-26 15:45 UTC, saltgen requested changes

2023-10-26 15:45 UTC, saltgen commented on internal/services/report_processor.go
> +func sliceK8sObjectToChunks(k8s_objects []kruizePayload.UpdateResult) [][]kruizePayload.UpdateResult {
@patilsuraj767 Additionally, I didn't get the reason for moving this function to current file.

2023-10-27 08:15 UTC, patilsuraj767 commented
/retest

2023-10-27 08:17 UTC, patilsuraj767 commented on internal/services/report_processor.go
> +func sliceK8sObjectToChunks(k8s_objects []kruizePayload.UpdateResult) [][]kruizePayload.UpdateResult {
I was getting linting issue because of cyclic imports. So I moved the function out of utils file.

2023-10-27 12:07 UTC, saltgen approved these changes

2023-10-27 12:21 UTC, patilsuraj767 commented on internal/services/report_processor.go
> +func sliceK8sObjectToChunks(k8s_objects []kruizePayload.UpdateResult) [][]kruizePayload.UpdateResult {
I had a look into `Dependency Inversion Principle` not sure how it fits in for this case but thanks for unblocking the PR. I will request you if possible you can implement it and create the new PR, will be happy to learn new things.

2023-10-27 12:41 UTC, patilsuraj767 commented
PR checks are failing because of some unknown issue. This has been reported to the QE team. 
I have tested the PR in ephemeral environment manually and everything look good. Hence merging the PR.

2023-10-27 12:41 UTC, merged