Removed tag added for testing and included cron job scheduling
RedHatInsights/ros-ocp-backend pull request #143
Opened 2023-10-30 06:09 UTC by chandrams

2023-10-30 09:17 UTC, chandrams commented
Worked with Gabor Burges to install the github app on the repo and I see the PR checks triggered as part of #112.  I have removed the temporary commitsha tag that I had added for testing and included cron job scheduling for this workflow. 

@patilsuraj767 @kgaikwad - Can you please review the changes, thanks.

2023-10-31 09:45 UTC, kgaikwad requested changes
@chandrams, added a inline comment about frequency of job run. 
As #112  is test PR, can we close it? Also, could you please confirm whether new PR will be raised by bot email `insights@redhat.com`?

2023-10-31 09:45 UTC, kgaikwad commented on .github/workflows/test-ros-kruize-rm.yml
> +    - cron: "5 0 * * *"
@chandrams do we really need to run cron job every 5 min?

2023-10-31 10:47 UTC, chandrams commented
> @chandrams, added a inline comment about frequency of job run. As #112 is test PR, can we close it? Also, could you please confirm whether new PR will be raised by bot email `insights@redhat.com`?

@kgaikwad - I did add a comment to close #112 but couldn't find the option to close. I will update the email id, thanks for pointing it out.

2023-11-01 08:29 UTC, kgaikwad commented on .github/workflows/test-ros-kruize-rm.yml
> +    - cron: "5 0 * * *"
@chandrams  my bad! I have considered `"5 * * * *"` & ignored zero value. +1

2023-11-01 08:38 UTC, kgaikwad commented
\retest

2023-11-01 08:54 UTC, kgaikwad commented
@chandrams  - also with this change, will it raise a separate PR everytime?

2023-11-01 09:06 UTC, kgaikwad approved these changes
LGTM :+1:

2023-11-01 10:04 UTC, merged