RHIROS-1408 Add PR creation template
RedHatInsights/ros-ocp-backend pull request #158
Opened 2023-11-22 07:26 UTC by srdeotarse

Similar to ROS for RHEL repository, added one for ROS OCP too.

Refer - https://github.com/RedHatInsights/ros-backend/blob/main/.github/pull_request_template.md

2023-11-22 08:28 UTC, r14chandra requested changes

2023-11-22 08:28 UTC, r14chandra commented on .github/pull_request_template.md
> +2. RHIROS-XXX Title
I think we are now using the `RHINENG` project. We can also include that. Otherwise, the rest looks fine.

2023-11-22 14:12 UTC, kgaikwad commented on .github/pull_request_template.md
> +3. RHIENG-XXX Title
```suggestion
3. RHINENG-XXX Title 
```

2023-12-04 10:31 UTC, upadhyeammit requested changes

2023-12-04 10:31 UTC, upadhyeammit commented on .github/pull_request_template.md
> +- [ ] DB Migration Added
As the ros-ocp has dependency with Kruize, do you think we should add an item 

```suggestion
- [ ] Does this change depend on specific version of Kruize
  - If yes what is the version no:
  - [ ] Is that image available in production or needs deployment?
- [ ] Bugfix
- [ ] New Feature
- [ ] Refactor
- [ ] Unittests Added
- [ ] DRY code
- [ ] Dependency Added
- [ ] DB Migration Added
```

2023-12-04 10:31 UTC, upadhyeammit commented on .github/pull_request_template.md
> +Please include the __context of this change__ here.
```suggestion
Please include the __context of this change__ here. If the change depends on Kruize add details about that as well!
```

2023-12-07 03:38 UTC, kgaikwad approved these changes

2023-12-28 09:54 UTC, merged

2023-12-28 09:54 UTC, kgaikwad commented
Thanks @srdeotarse!