Deploys Kruize UI
RedHatInsights/ros-ocp-backend pull request #161
Opened 2023-11-30 12:46 UTC by bhanvimenghani

This pr aims to make changes to the clowdapp yaml file to deploy kruize ui along with kruize and ros ocp.

2023-12-05 05:58 UTC, patilsuraj767 requested changes
Thanks for the PR @bhanvimenghani. I have added the comment below I think you will first need to check clowder document. 
Also I think your IDE is formatting the whole document that is the reason I can see many changes under `Files Changed` tab. If you are using vscode can you please disable/remove any custom yaml plugin which is installed and then try again to format the file. 
If that didn't work can you also check this - https://stackoverflow.com/questions/61978428/yaml-file-formatting-in-vscode

2023-12-05 05:58 UTC, patilsuraj767 commented on kruize-clowdapp.yaml
> +              subPath: nginx.conf
You cannot directly declare pods here, You will need to create another deployment. Please refer CloudApp API reference doc - https://consoledot.pages.redhat.com/clowder/dev/api_reference.html#k8s-api-github-com-redhatinsights-clowder-apis-cloud-redhat-com-v1alpha1-podspec

2025-02-04 11:16 UTC, saltgen commented
Closing out this PR as stale

2025-02-04 11:16 UTC, saltgen commented
Closing out this PR as stale

2025-02-04 11:16 UTC, closed without merging