Update kruize config to include cloudwatch service
RedHatInsights/ros-ocp-backend pull request #208
Opened 2024-04-19 04:10 UTC by kusumachalasani

## Update kruize config to include cloudwatch service

## Why do we need this change? :thought_balloon:

Include the ENV changes of Kruize to include Cloudwatch configuration.

## Documentation update? :memo:

- [ ] Yes
- [x] No

## Security Checklist :lock:

Upon raising this PR please go through [RedHatInsights/secure-coding-checklist](https://github.com/RedHatInsights/secure-coding-checklist)

## :guardsman: Checklist :dart:

- [ ] Does this change depend on specific version of Kruize
  - If yes what is the version no: <Yet to release>
  - [ ] Is that image available in production or needs deployment?
- [ ] Bugfix
- [x] New Feature
- [ ] Refactor
- [ ] Unittests Added
- [ ] DRY code
- [ ] Dependency Added
- [ ] DB Migration Added

2024-04-24 04:11 UTC, kusumachalasani commented on scripts/kruizecloudwatchcofig.json
> +}
The configuration format employed by kruize resembles the following. Given that the ROS format incorporates a two-level structure to get the cloudwatch config, kruize cannot directly interpret this configuration.
 To align with the kruize format, I've generated a new file with the appropriate structure for kruize's interpretation. Alternatively, we might consider integrating the necessary format into the existing configuration file.
```
kruizeconfigjson: |
    {
      "clustertype":"kubernetes",
      "k8stype" : "minikube",
      "authtype": "",
      "monitoringagent":"prometheus",
      "monitoringservice":"prometheus-k8s",
      "monitoringendpoint":"prometheus-k8s",
      "savetodb":"true",
      "dbdriver":"jdbc:postgresql://",
      "hibernate": {
        "dialect": "org.hibernate.dialect.PostgreSQLDialect",
        "driver": "org.postgresql.Driver",
        "c3p0minsize": 2,
        "c3p0maxsize": 5,
        "c3p0timeout": 300,
        "c3p0maxstatements": 50,
        "hbm2ddlauto": "update",
        "showsql": "true"
      },
      "cloudwatch": {
        "accessKeyId": "",
        "secretAccessKey": "",
        "region": "",
        "logGroup": "kruize-logs",
        "logStream": "kruize-stream",
        "logLevel": "INFO"
      }
    }
    ```

2024-04-24 04:18 UTC, patilsuraj767 commented on scripts/kruizecloudwatchcofig.json
> +}
It is not under our control, We will not be able to provide a json file in kruize format. [cdappconfig.json ](https://github.com/RedHatInsights/ros-ocp-backend/blob/main/scripts/cdappconfig.json) file and `ACG_CONFIG` env variable is set directly by clowder operator.

2024-04-24 08:38 UTC, kusumachalasani commented on scripts/kruizecloudwatchcofig.json
> +}
Updated the structure in kruize accordingly.

2024-04-24 14:27 UTC, saltgen requested changes

2024-04-24 14:27 UTC, saltgen commented on kruize-clowdapp.yaml
> +  value: "kruize-stream"
@kusumachalasani Please update the stream value to `kruize-recommendations` i.e. the Openshift deployment name, the current one seems a bit generic.

2024-04-25 06:15 UTC, saltgen submitted a review, later dismissed
Thank you for the changes @kusumachalasani! LGTM 👍🏼

2024-04-25 06:29 UTC, saltgen commented
@kusumachalasani Since Kruize is upstream I think the value for CW log group the same should be configurable similar to log stream name.
In case the value is hard-coded in Kruize codebase atm, do you prefer the same for now?

2024-04-25 09:04 UTC, kusumachalasani commented
> @kusumachalasani Since Kruize is upstream I think the value for CW log group the same should be configurable similar to log stream name. In case the value is hard-coded in Kruize codebase atm, do you prefer the same for now?

All the variables (including logGroup and logStream) related to CW logging are configurable in kruize upstream.  If it is not configured through both json and ENV variables, it picks up the default ones. In kruize-clowdapp.yaml I didn't mention logGroup as part of an ENV because Suraj mentioned that it cannot be changed and will be picked up from the clowder json.

2024-04-26 08:40 UTC, saltgen commented
> > @kusumachalasani Since Kruize is upstream I think the value for CW log group the same should be configurable similar to log stream name. In case the value is hard-coded in Kruize codebase atm, do you prefer the same for now?
> 
> All the variables (including logGroup and logStream) related to CW logging are configurable in kruize upstream. If it is not configured through both json and ENV variables, it picks up the default ones. In kruize-clowdapp.yaml I didn't mention logGroup as part of an ENV because Suraj mentioned that it cannot be changed and will be picked up from the clowder json.

I don't see an issue if the group is mentioned explicitly, although it should work fine if the defaults are picked up from something like `clowder.LoadedConfig` and then used for log streaming.
Anyways, as far as changes on ROS side are concerned, we are good.

2024-04-26 08:42 UTC, saltgen approved these changes

2024-04-26 08:44 UTC, merged