Testing Do not Merge
RedHatInsights/ros-ocp-backend pull request #273
Opened 2024-11-06 12:11 UTC by yash2189

## PR Title :boom:

Please title this PR with a summary of the change, along with the JIRA card number.

Suggested formats: 

1. Fixes/Refs #RHIROS-XXX - Title
2. RHIROS-XXX Title
3. RHINENG-XXX Title 

Feel free to remove this section from PR description once done.

## Why do we need this change? :thought_balloon:

Please include the __context of this change__ here. If the change depends on Kruize add details about that as well!

## Documentation update? :memo:

- [ ] Yes
- [ ] No

## Security Checklist :lock:

Upon raising this PR please go through [RedHatInsights/secure-coding-checklist](https://github.com/RedHatInsights/secure-coding-checklist)

## :guardsman: Checklist :dart:

- [ ] Does this change depend on specific version of Kruize
  - If yes what is the version no:
  - [ ] Is that image available in production or needs deployment?
- [ ] Bugfix
- [ ] New Feature
- [ ] Refactor
- [ ] Unittests Added
- [ ] DRY code
- [ ] Dependency Added
- [ ] DB Migration Added

## Additional :mega:

Feel free to add any other relevant details such as __links, notes, screenshots__, here.

2024-11-12 11:38 UTC, saltgen requested changes
@yash2189 Please squash commits and add a relevant commit msg

2024-11-12 11:38 UTC, saltgen requested changes
@yash2189 Please squash commits and add a relevant commit msg

2024-11-13 11:59 UTC, saltgen approved these changes

2024-11-13 11:59 UTC, saltgen approved these changes

2024-11-13 11:59 UTC, merged

2026-07-11 19:58 UTC, pgarciaq commented
## Industry Context for Capacity Constant

The proposed increase of `groupedAll` from **256** to **4,096** is informed by industry container density data:

| Source | Metric | Value |
|--------|--------|-------|
| [CNCF Annual Survey 2025](https://www.cncf.io/reports/cncf-annual-survey-2025/) | Containers per cluster (median) | **~370** |
| [Datadog Container Report 2025](https://www.datadoghq.com/container-report/) | Containers per cluster (median) | **250+** |
| [Datadog Container Report 2025](https://www.datadoghq.com/container-report/) | Top-percentile clusters | **5,000+** |

### Why 4,096?

Each CSV file produces one `DigestKey` per unique (container, day, schedule_type) combination. For a typical nise-generated CSV with ~100K rows covering one day of data:
- A 250-container cluster → ~250 keys → no rehash from 4,096
- A 370-container cluster (CNCF median) → ~370 keys → no rehash from 4,096
- A 1,000-container cluster → ~1,000 keys → no rehash from 4,096
- A 5,000-container cluster (top percentile) → ~5,000 keys → 1 rehash (4,096 → 8,192)
- A 100K-container cluster (benchmark extreme) → ~84,000 keys → still only ~5 rehashes from 4,096 (vs. 9 from 256)

### Companion constants

| Constant | Value | Justification |
|----------|-------|---------------|
| `defaultGroupedAllCapacity` | 4,096 | Covers ≥95% of clusters without any rehash |
| `defaultGroupedBHCapacity` | 1,024 | BH subset: typically 30–50% of containers have BH schedules |
| `defaultNodeAccumCapacity` | 256 | Covers clusters up to 256 nodes (~13× headroom over typical 19-node clusters) |

### Memory cost of over-allocation

An empty `map[DigestKey][]metricSample` bucket costs ~8 bytes. At 4,096 initial capacity: `4,096 × 8B ≈ 32 KB` — completely negligible even on a 512Mi pod. The benefit (eliminating 6 rehash+copy cycles per file for typical clusters) far outweighs the cost.

See also: [Performance Audit v4 — Appendix: Industry Context for Capacity Constants](../docs/performance/native-engine-audit-v4-2026-07.md)