RHINENG-14146  Optimize Get Recommendations Query
RedHatInsights/ros-ocp-backend pull request #282
Opened 2024-12-09 12:53 UTC by saltgen

## Why do we need this change? :thought_balloon:

The current sql query is expensive considering there is a lot of records to sift through.
Analysis details are present in the JIRA card.

That said, some important details are provided in the Additional section below.

## Documentation update? :memo:

- [ ] Yes
- [ ] No

## Security Checklist :lock:

Upon raising this PR please go through [RedHatInsights/secure-coding-checklist](https://github.com/RedHatInsights/secure-coding-checklist)

## :guardsman: Checklist :dart:

- [ ] Does this change depend on specific version of Kruize
  - If yes what is the version no:
  - [ ] Is that image available in production or needs deployment?
- [ ] Bugfix
- [ ] New Feature
- [ ] Refactor
- [ ] Unittests Added
- [ ] DRY code
- [ ] Dependency Added
- [ ] DB Migration Added

## Additional :mega:

### Indexes added

clusters (last_reported_at)
recommendation_sets (workload_id)
workloads (cluster_id)

### Other Optimizations

- Discarding usage of postgres' DATE method in queries
- queryParams object is now a native interface

### Query Diffs

### GetRecommendationSet

### Old

```
SELECT "recommendation_sets"."id","recommendation_sets"."workload_id","recommendation_sets"."container_name","recommendation_sets"."monitoring_start_time","recommendation_sets"."monitoring_end_time","recommendation_sets"."recommendations","recommendation_sets"."updated_at" FROM "recommendation_sets" 
                        JOIN workloads ON recommendation_sets.workload_id = workloads.id
                        JOIN clusters ON workloads.cluster_id = clusters.id
                        JOIN rh_accounts ON clusters.tenant_id = rh_accounts.id
                 WHERE rh_accounts.org_id = '3340851' AND DATE(recommendation_sets.monitoring_end_time) >= '1970-01-01' AND DATE(recommendation_sets.monitoring_end_time) <= '2024-12-02' ORDER BY clusters.last_reported_at LIMIT 10;

```

### New

```
SELECT recommendation_sets.id, recommendation_sets.container_name AS container, workloads.namespace AS project, workloads.workload_name as workload, workloads.workload_type, clusters.source_id, clusters.cluster_uuid, clusters.cluster_alias, clusters.last_reported_at AS last_reported, recommendation_sets.recommendations FROM "recommendation_sets" 
			JOIN workloads ON recommendation_sets.workload_id = workloads.id
			JOIN clusters ON workloads.cluster_id = clusters.id
			JOIN rh_accounts ON clusters.tenant_id = rh_accounts.id
		 WHERE rh_accounts.org_id = '3340851' AND recommendation_sets.monitoring_end_time >= '1970-01-01 00:00:00' AND recommendation_sets.monitoring_end_time <= '2024-12-09 12:07:47.503' ORDER BY clusters.last_reported_at DESC LIMIT 10
```

### GetRecommendationSetByID

### Old

```
SELECT "recommendation_sets"."id","recommendation_sets"."workload_id","recommendation_sets"."container_name","recommendation_sets"."monitoring_start_time","recommendation_sets"."monitoring_end_time","recommendation_sets"."recommendations","recommendation_sets"."updated_at" FROM "recommendation_sets" JOIN workloads ON recommendation_sets.workload_id = workloads.id JOIN clusters ON workloads.cluster_id = clusters.id JOIN rh_accounts ON clusters.tenant_id = rh_accounts.id WHERE rh_accounts.org_id = '3340851' AND recommendation_sets.id = '4514582e-a156-47ae-8cc7-705a1dd3207b' ORDER BY "recommendation_sets"."id" LIMIT 1
```

### New

```
SELECT recommendation_sets.id, recommendation_sets.container_name AS container, workloads.namespace AS project, workloads.workload_name as workload, workloads.workload_type, clusters.source_id, clusters.cluster_uuid, clusters.cluster_alias, clusters.last_reported_at AS last_reported, recommendation_sets.recommendations FROM "recommendation_sets" 
			JOIN workloads ON recommendation_sets.workload_id = workloads.id
			JOIN clusters ON workloads.cluster_id = clusters.id
			JOIN rh_accounts ON clusters.tenant_id = rh_accounts.id
		 WHERE rh_accounts.org_id = '3340851' AND recommendation_sets.id = '32a5d36c-aec1-41d7-b19f-5fef015a930a' ORDER BY "recommendation_sets"."id" LIMIT 1
```

2024-12-09 13:02 UTC, saltgen commented
I'll fix the test soon, please feel free to go through the other changes meanwhile.

2024-12-16 11:22 UTC, kgaikwad requested changes
Changes look good to me. :+1:  I will continue reviewing latest updated changes specific to date field. 
Added just two inline suggestions. Please feel free to skip if it doesn't make sense. 
Thanks!

2024-12-18 13:21 UTC, upadhyeammit commented
/retest

2024-12-19 13:02 UTC, upadhyeammit reviewed
The `query` var in `GetRecommendationSets` and `GetRecommendationSetByID` is exactly same part from a filter `Where("recommendation_sets.id = ?", recommendationID)` .  This is good candidate to consolidate and take out in another common function.

2024-12-23 14:16 UTC, saltgen commented on internal/api/handlers.go
> +		recommendationData["recommendations"] = UpdateRecommendationJSON(handlerName, recommendation.ID, recommendation.ClusterUUID, unitChoices, setk8sUnits, recommendation.Recommendations)
I think you'll like this 🙂 
https://github.com/RedHatInsights/ros-ocp-backend/pull/282/commits/579879c9f69970974b56bdef4a3c6155ef894bd5

2024-12-24 07:23 UTC, upadhyeammit commented
/retest

2024-12-24 07:36 UTC, upadhyeammit commented
On IQE I can see its failing because of syntax error, however I dont see this locally? hmm.. is it because locally I am on 1.22 version of Go? need to check,
~~~
{"file":"/go/src/app/internal/api/handlers.go:118","func":"github.com/redhatinsights/ros-ocp-backend/internal/api.GetRecommendationSetList","level":"error","msg":"unable to fetch records from databaseERROR: syntax error at or near \")\" (SQLSTATE 42601)","service":"rosocp-api","time":"2024-12-24T07:31:53Z"}
{"time":"2024-12-24T07:31:53.233083919Z","id":"","remote_ip":"10.131.11.30","host":"ros-ocp-backend-api.ephemeral-xbkkoa.svc:8000","method":"GET","uri":"/api/cost-management/v1/recommendations/openshift?cluster=ros_ocp_cluster_caqjsNZzY&start_date=2024-12-17","user_agent":"OpenAPI-Generator/1.0.0/python","status":200,"error":"","latency":11045462,"latency_human":"11.045462ms","bytes_in":0,"bytes_out":361}
~~~

2024-12-24 08:44 UTC, saltgen commented
> On IQE I can see its failing because of syntax error, however I dont see this locally? hmm.. is it because locally I am on 1.22 version of Go? need to check,
> 
> ```
> {"file":"/go/src/app/internal/api/handlers.go:118","func":"github.com/redhatinsights/ros-ocp-backend/internal/api.GetRecommendationSetList","level":"error","msg":"unable to fetch records from databaseERROR: syntax error at or near \")\" (SQLSTATE 42601)","service":"rosocp-api","time":"2024-12-24T07:31:53Z"}
> {"time":"2024-12-24T07:31:53.233083919Z","id":"","remote_ip":"10.131.11.30","host":"ros-ocp-backend-api.ephemeral-xbkkoa.svc:8000","method":"GET","uri":"/api/cost-management/v1/recommendations/openshift?cluster=ros_ocp_cluster_caqjsNZzY&start_date=2024-12-17","user_agent":"OpenAPI-Generator/1.0.0/python","status":200,"error":"","latency":11045462,"latency_human":"11.045462ms","bytes_in":0,"bytes_out":361}
> ```

I'll take a look

2025-01-07 09:48 UTC, saltgen commented on internal/api/utils.go
> +	queryParams["recommendation_sets.monitoring_end_time >= ?"] = startTimestamp.Truncate(time.Second)
Yes it is, in case a value for the query param is available at L#76

2025-01-07 09:50 UTC, saltgen commented on internal/api/utils.go
> +		startTimestamp = firstOfMonth
IMO, this variable `firstOfMonth` helps with the readability at the if block in L#78

2025-01-07 09:53 UTC, saltgen commented on internal/api/utils.go
> +		endTimestamp = now
This would work in case we don't expect any values for the query param `end_date`.
Not sure if I'm missing something.

2025-01-07 10:01 UTC, saltgen commented on internal/api/api_test.go
> +	endTime := time.Date(2023, 3, 24, 0, 0, 0, 0, time.UTC).Truncate(time.Second)
This is the diff of values,

w Truncate
```
2025-01-01 00:00:00 UTC
```
w/o Truncate
```
2025-01-01 00:00:00.000000000 UTC
```
Truncate also trims the ns portion.

2025-01-07 10:02 UTC, saltgen commented on internal/api/utils.go
> +	queryParams["recommendation_sets.monitoring_end_time <= ?"] = endTimestamp.Truncate(time.Second)
ditto

2025-01-07 11:09 UTC, saltgen commented on internal/api/utils.go
> +		endTimestamp = now
I think we should have the time portion available in the timestamp especially when the query param `end_time` value has not been provided

2025-01-07 11:21 UTC, saltgen commented on internal/api/api_test.go
> +	endTime := time.Date(2023, 3, 24, 0, 0, 0, 0, time.UTC).Truncate(time.Second)
removed Truncate usages here

2025-01-07 11:21 UTC, saltgen commented on internal/api/utils.go
> +	queryParams["recommendation_sets.monitoring_end_time >= ?"] = startTimestamp.Truncate(time.Second)
removed Truncate usage here

2025-01-07 11:21 UTC, saltgen commented on internal/api/utils.go
> +	queryParams["recommendation_sets.monitoring_end_time <= ?"] = endTimestamp.Truncate(time.Second)
removed Truncate usage here

2025-01-09 12:24 UTC, kgaikwad commented on internal/api/utils.go
> +		endTimestamp = endTimestamp.Add(24 * time.Hour)
@upadhyeammit, what would prefer to have your opinion as well on this?

2025-01-13 07:51 UTC, upadhyeammit commented on internal/api/utils.go
> +		endTimestamp = endTimestamp.Add(24 * time.Hour)
It took me bit of time to understand whats happening here. I can see we are adding 24hours(a day) to user provided date for returning the recommendations upto user provided date. However the condition for filter has `<=`; so do we need it?
~~~
queryParams["recommendation_sets.monitoring_end_time <= ?"] = endTimestamp
~~~

2025-01-22 12:38 UTC, saltgen commented on internal/api/utils.go
> +		endTimestamp = endTimestamp.Add(24 * time.Hour)
Removed the `=` from `queryParams["recommendation_sets.monitoring_end_time <= ?"] = endTimestamp`
Regarding `start_date` I think we should be fine, the 24 Hrs delta is being added only for user provided end_date

2025-01-22 12:38 UTC, saltgen commented on internal/model/recommendation_set.go
> +func (r *RecommendationSet) GetRecommendationSet(orgID string, user_permissions map[string][]string, opts ...GetRecommendationOptions,
Change pushed

2025-01-22 13:19 UTC, saltgen commented
/retest

2025-01-27 10:13 UTC, kgaikwad approved these changes
Codewise changes look good to me now :+1:  
@saltgen, could you please check why konflux pipeline is not happy?

2025-01-27 10:13 UTC, kgaikwad commented
\retest

2025-01-28 08:36 UTC, saltgen commented
/retest

2025-01-28 09:36 UTC, saltgen commented
/retest

2025-01-28 13:08 UTC, upadhyeammit approved these changes

2025-01-28 13:08 UTC, upadhyeammit commented
/retest

2025-01-28 13:32 UTC, upadhyeammit commented
/retest

2025-01-28 14:11 UTC, merged

2026-07-12 14:26 UTC, pgarciaq commented
Resolved: replaced single-`}` heuristic with brace-depth tracking in statement_timeout_lint_test.go. Nested braces inside setStatementTimeout no longer prematurely end the exempt region.